#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

script/gofumpt -w internal/*/*.go cmd/*/*.go

find script -type f -not -name 'bootstrap-bindown.sh' |
  grep -v "/.*/" |
  xargs script/shfmt -w -i 2 -ci -sr

script/shfmt -w -i 2 -ci -sr internal/build-bootstrapper/assets/*.sh
