#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

script/bindown -q install gofumpt shfmt

bin/gofumpt -w internal/*/*.go cmd/*/*.go

find script -type f -not -name 'bootstrap-bindown.sh' -print0 | xargs -0 bin/shfmt -w -i 2 -ci -sr
