#!/bin/bash

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

usage_pattern="<!--- start usage output --->*<!--- end usage output --->"

usag_sub="$(cat <<EOF
<!--- start usage output --->
\`\`\`
$(COLUMNS=100 script/bindown --help)
\`\`\`
<!--- end usage output --->
EOF
)"

readme="$(cat README.md)"
echo "${readme//$usage_pattern/$usag_sub}" > README.md
