#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

if [ "$1" = "--check" ]; then
  [ -z "$(git status --porcelain)" ] || {
    git status
    echo 1>&2 "Running 'script/generate --check' requires a clean git working tree. Please commit or stash changes and try again."
    exit 1
  }
  script/generate
  [ -z "$(git status --porcelain)" ] || {
    git status
    echo 1>&2 "script/generate resulted in changes. Please commit changes (or 'git reset --hard HEAD' if you aren't ready to commit changes)."
    git diff
    exit 1
  }
  exit 0
fi

. script/goenv

make -s bin/yq

# We need a copy of bindown.schema.json in both root and internal/bindown
yq read --prettyPrint -j bindown.schema.yml > bindown.schema.json
yq read --prettyPrint -j bindown.schema.yml > internal/bindown/bindown.schema.json

go generate ./...
COLUMNS=100 script/bindown --help > ./docs/clihelp.txt
script/generate-readme
