#!/bin/bash

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

go run ./internal/genjsonschema > bindown.schema.json
cp bindown.schema.json ./internal/bindown/bindown.schema.json
script/yq -P . < bindown.schema.json > bindown.schema.yml
