#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

. script/goenv

go "$@"

#mkdir -p tmp/go
## shellcheck disable=SC2068
#PATH="$(pwd)/bin:$PATH" GOPATH="$(pwd)/tmp/go" go "$@"
