#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

make -s bin/go
PATH="$(pwd)/bin:$PATH"

if [ -n "$GOROOT" ]; then
  GOROOT="$(pwd)/bin/$(dirname -- "$(dirname -- "$(readlink bin/go)")")"
  export GOROOT
fi
