#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

. script/goenv

make -s bin/golangci-lint bin/shellcheck

bin/golangci-lint run
(
  GLOBIGNORE="script/bootstrap-bindown.sh";
  bin/shellcheck script/*
)
