#!/bin/sh

set -ex

SCRIPT_DIR="$(CDPATH="" cd -- "$(dirname -- "$0")" && pwd)"

CDPATH="" cd -- "$SCRIPT_DIR/.."

[ -n "$GITHUB_TOKEN" ] || {
  echo GITHUB_TOKEN must be set
  exit 1
}

. script/goenv

make -s bin/goreleaser bin/semver-next bin/jq bin/build-bootstrapper bin/gh

GITHUB_SHA="${GITHUB_SHA:-"$(git rev-parse HEAD)"}"
GITHUB_REPOSITORY="${GITHUB_REPOSITORY:-"WillAbides/bindown"}"

bin/semver-next "$GITHUB_REPOSITORY" -r "$GITHUB_SHA" --create-tag --require-labels

git fetch --tags

bin/goreleaser release
TAG="$(bin/jq -r '.tag' dist/metadata.json)"
bin/build-bootstrapper -tag "$TAG" > bootstrap-bindown.sh
bin/gh release upload "$TAG" bootstrap-bindown.sh
