#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

[ -n "$GITHUB_TOKEN" ] || {
  echo GITHUB_TOKEN must be set
  exit 1
}

AUTH_HEADER="Authorization: token $GITHUB_TOKEN"

[ -f "dist/bootstrap-bindown.sh" ] || {
  echo dist/bootstrap-bindown.sh is required
  exit 1
}

TAG="$(grep "^TAG=" dist/bootstrap-bindown.sh | cut -d\" -f2)"

release_id="$(curl -s -H "$AUTH_HEADER" "https://api.github.com/repos/WillAbides/bindown/releases/tags/$TAG" | jq .id)"
upload_url="https://uploads.github.com/repos/WillAbides/bindown/releases/$release_id/assets?name=bootstrap-bindown.sh"
echo "$upload_url"

file_content="$(cat dist/bootstrap-bindown.sh)"

curl -X POST -H "$AUTH_HEADER" -H "Content-Type: application/text" -d "$file_content" "$upload_url"
